default_language_version:
  python: python3.7
default_stages: [push]
exclude: "^$"
fail_fast: false
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: flake8
        args: [--max-line-length=131]
      - id: pretty-format-json
      - id: trailing-whitespace
  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
        stages: [commit-msg]
